### ISSUE TITLE
add information about bug bbq

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/docs.carpentries.org#129]
Please add info about how to schedule a bug bbq and how to set up a bug bbq website to http://docs.carpentries.org/topic_folders/lesson_development/bug_bbq.html. This isn't urgent and can be done after the handbook release.

**Comment by fmichonneau** [comment]
I think the format of the bug BBQ might chance in the next iteration so leave it as is for now, and we'll revisit as we plan the next one.

**Comment by maneesha** [comment]
@ErinBecker  @fmichonneau  Do we have updated information about Bug BBQs?

**Comment by ErinBecker** [comment]
We're not planning any Bug BBQs for the next two quarters, so let's leave this open and mark it to look at later.

**Comment by maneesha** [comment]
Do we still do Bug BBQs? Do we want to keep this open?

**Comment by fmichonneau** [comment]
let's close, we can re-open later if we decide to do bug bbq again.
