### ISSUE TITLE
SVG error for annotate lesson life cycle

### ISSUE THREAD

**Issue by zkamvar** [carpentries/docs.carpentries.org#279]
There's an SVG error in the annotated lesson lifecycle diagram:

https://github.com/carpentries/docs.carpentries.org/blob/5b0b8565d1053a301ba5fa5a8f30867bb95b5167/source/img/life_cycle_annotated.svg#L3

It looks like some tool inserted a bunch of ampersands and `ns_ai` as the namespace? You might be able to remove that line and have a valid SVG.

**Comment by maneesha** [comment]
Thanks for catching this @zkamvar 

@tobyhodges - what is the difference meant to be between `life_cycle_annotated.svg` and `life_cycle.svg`?  The non-annotated one renders correctly.

**Comment by tobyhodges** [comment]
From local testing it looks like there was something wonky about the Library Carpentry logo. Your change in #280 looks good to me, thanks. (Also I learned the existence of online SVG validators - thanks!)
