### ISSUE TITLE
Future section: guidelines on working with carpentries data

### ISSUE THREAD

**Issue by tracykteal** [carpentries/docs.carpentries.org#285]
This is an issue for adding in the future, as we further develop guidelines, a section of the handbook on working with carpentries data.

**Comment by fmichonneau** [comment]
along these lines, I think we should identify the stakeholders:

- public
- instructors
- workshop hosts
- carpentry staff
- ...

and articulate who has access to what.

**Comment by maneesha** [comment]
@fmichonneau  I am closing this here since we have larger projects around data policies. We can make documentation updates based on that work.
