### ISSUE TITLE
Move lesson example's style guide to handbook

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/docs.carpentries.org#436]
http://carpentries.github.io/lesson-example/06-style-guide/index.html need to be moved to here.

**Comment by maneesha** [comment]
Thanks @rgaiacs 
As an end user, where in the Handbook would it make most sense for this to go for you?

**Comment by rgaiacs** [comment]
> As an end user, where in the Handbook would it make most sense for this to go for you?

https://docs.carpentries.org/topic_folders/communications/style-guide.html It should have a section about code.

**Comment by brownsarahm** [comment]
the intro to the Handbook Style Guide says that it doesn't necessarily apply to lessons though, should that also change if we pull the current lesson style guide into the Handbook Style Guide?

**Comment by rgaiacs** [comment]
> the intro to the Handbook Style Guide says that it doesn't necessarily apply to lessons though

I read it as "this Style Guide doesn't apply to the lessons in Spanish" or "this Style Guide doesn't apply to the lesson that we are prototyping and is being lead by instructors only from country C". I think that for the the main lessons we should use the Style Guide.

**Comment by brownsarahm** [comment]
it says, in the second paragraph(emphasis mine):

> We will adhere to a similar style on our website and in other material we make widely available such as blog posts, **but not necessarily in lessons**

I agree that for the main lessons we *should* use the Style Guide, but if we are going to, we should remove that phrase from the style guide.

**Comment by maneesha** [comment]
@zkamvar  I **think** this falls under the work you do.  Is this something we should keep open?

**Comment by maneesha** [comment]
Pinging @zkamvar

**Comment by maneesha** [comment]
Checking in @zkamvar

**Comment by bencomp** [comment]
I just mentioned in carpentries/lesson-example#258 that the link to the [Style guide in the Handbook](https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html) is broken.

As a maintainer/lesson contributor, I would like to have a single style guide for lesson contents. I feel that adding (or rather moving) the current style guide from the lesson example to the Handbook Style guide would make the latter even less easy to navigate. (The table of contents on the left only lists letters, so I have to search or browse the whole page to see if the guide could answer my question.)

The lesson example style guide helps with *markup* (and Markdown), whereas the Handbook's Style guide is focused on the *text contents*.
It could help to make this distinction more clearly and to add a reference to the lesson style guide, which of course will soon be the Workbench's guide.

**Comment by bencomp** [comment]
I rediscovered the [Lesson Development handbook](https://cdh.carpentries.org) today and wonder if *that* should be the place for a lesson style guide.

**Comment by maneesha** [comment]
@tobyhodges  Do you want to keep this issue active in the new handbook? If it is no longer relevant, we can close this issue.
