### ISSUE TITLE
Programs vs Programmes

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/docs.carpentries.org#455]
The [Style Guide](https://docs.carpentries.org/topic_folders/communications/style-guide.html) says

>  To ensure that the style guide is as widely applicable as possible, UK English spellings and usage will be used in favour of American spelling.

Could you include the use of program vs programme to the style guide?

**Comment by maneesha** [comment]
Thanks for bringing this up @rgaiacs 
We use the word "program" a lot - especially as we refer to all our "lesson programs" of The Carpentries and when we talk about writing "computer programs" in our work.  I could use some guidance on how we should implement this --- maybe from @serahrono  from a communications perspective, and from anyone else who can provide a perspective outside of American English.

Some references I've looked at:
https://www.grammarly.com/blog/program-programme/
https://grammarist.com/spelling/program-programme/

**Comment by maneesha** [comment]
@serahrono We use the word "program" a lot, in many different contexts.  Do we want to consider using alternate spellings in our documentation?

**Comment by maneesha** [comment]
@OscarSiba I am reviewing issues in our old handbook repo so we can close them out or migrate them as needed.  Please advise about this. Thanks!

**Comment by OscarSiba** [comment]
We use British spelling for everything except "programs". So please close the issue and don't transfer it. We won't be making any updates in this regard.
