### ISSUE TITLE
Migrate Maintainers documentation from swcarpentry/lesson-example

### ISSUE THREAD

**Issue by remram44** [carpentries/docs.carpentries.org#47]
I'm told from @maneesha that this is supposed to replace all the current sources of information, so the Maintainers' documentation should be moved as well.

Currently our main source of documentation is https://github.com/swcarpentry/lesson-example. Should the content be moved here, and the lesson-example repo turned back into an example of lesson?

Essentially a duplicated of https://github.com/swcarpentry/lesson-example/issues/164.

**Comment by ErinBecker** [comment]
@remram44 - It seems like there are definitely parts of the lesson-example repo that belong in this handbook, for example: http://swcarpentry.github.io/lesson-example/08-maintenance/index.html. However, not all of the information in lesson-example is a good fit for the handbook, particularly the portions that include formatted code blocks and figures (for example: http://swcarpentry.github.io/lesson-example/04-formatting/index.html)

For the other sections of this handbook, we're thinking about documentation vs. curriculum. For example: 
[Maintainer Onboarding](https://carpentries.github.io/maintainer-onboarding/) vs. [Maintainer documentation](http://docs.carpentries.org/topic_folders/maintainers/index.html)
[Trainer Training](https://carpentries.github.io/trainer-training/) (incomplete) vs [Instructor training documentation](http://docs.carpentries.org/topic_folders/instructor_training/index.html)

I can see some of the materials currently in lesson-example being migrated to the Maintainer documentation in this handbook and some migrating to a new [Curriculum Development curriculum](https://carpentries.github.io/curriculum-development/) (in planning stages). 

I'll work on moving over some of the documentation related info from this repo to get us started with this reorganization.

**Comment by maneesha** [comment]
@ErinBecker  Can we close this now that the CDH is out?

**Comment by remram44** [comment]
You should probably remove the information from lesson-example and update the numerous links from other lessons/handbooks. Those can probably be found automatically without too much work.

**Comment by maneesha** [comment]
@ErinBecker  Should we keep this open, or does the new Curriculum Development Handbook (linked to in this Handbook's [Lesson Development](https://docs.carpentries.org/topic_folders/lesson_development/index.html) section) cover this?

**Comment by maneesha** [comment]
@remram44 [lesson-example](http://carpentries.github.io/lesson-example/) was updated following the release of the Curriculum Development Handbook.  

What are the other lessons or handbooks you might suggest changes to?

**Comment by remram44** [comment]
Individual lesson README's ([example](https://github.com/swcarpentry/sql-novice-survey/blob/08ec393beefdb385c83178bbc285f4f634ca8b46/README.md)) still refer to it as:

> the lesson template documentation for instructions on formatting, building, and submitting material

and the CONTRIBUTING ([example](https://github.com/swcarpentry/sql-novice-survey/blob/08ec393beefdb385c83178bbc285f4f634ca8b46/CONTRIBUTING.md#where-to-contribute)):

> https://github.com/carpentries/lesson-example, which documents the format of our lessons

Those should probably point straight to the handbook instead? (though there is a link from the example to the handbook)

**Comment by maneesha** [comment]
Thanks for these examples @remram44 
What would you suggest @ErinBecker and @fmichonneau ?

**Comment by ErinBecker** [comment]
Thanks for the ping @maneesha. This one is a little complicated. Can we plan on talking through it at one of our upcoming meetings and write out a document together of what goes where?

**Comment by maneesha** [comment]
@zkamvar and @fmichonneau Is this something we are still working on?

**Comment by fmichonneau** [comment]
I think this can be closed for now as we will be reviewing the organization of our information across our websites in upcoming quarters and this will be addressed then.
