### ISSUE TITLE
provide guidance on use of "dataframe" vs "data frame"

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/docs.carpentries.org#473]
There is inconsistent use of dataframe (all one word) and data frame in some of our lessons, especially those in alpha or beta stages of development - it would be good to provide guidance on the accepted form (which I guess should be "data frame") in the style guide.

**Comment by maneesha** [comment]
I actually don't know the answer to that for sure... It seems that [Python/Pandas uses DataFrame](https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html) (one word, no spaces, camel case) while [R uses data frame](https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Data-frames) (two words, space, lower  case). 

@tobyhodges  is this something that's more lesson specific or something that should be addressed in this handbook?

**Comment by maneesha** [comment]
Tagging @zkamvar - is this a lesson infrastructure question? Not sure where this question would be best handled.

**Comment by zkamvar** [comment]
I think this is an infrastructure question and I think it's best handled here in the handbook since it would affect more than one lesson.
