### ISSUE TITLE
Maintainers section seems incomplete

### ISSUE THREAD

**Issue by maneesha** [carpentries/docs.carpentries.org#48]
From one of the maintainers:

> I don't find all the information I expect in the maintainer section such as:
> - MAINTAINERS
>       * Step for Maintainer Onboarding process
>       * Template emails
>       * Maintainer Onboarding lesson (https://carpentries.github.io/maintainer-onboarding/index.html)
>       * Maintainer operation i.e. day to day work with information such as:
>                 - How to deal with issues (most information is available in the Maintainer Onboarding lesson)
>                     + How to label issues
>                     +  How to get help (slack, help-wanted label, etc.)
>                  - How to update the lesson template style (something I have never done so I don't know anything about it)
>                  - How to be kept informed (slack, maintainer meetings, lesson development)
>                    
>        * Step for scheduling a Bonanza/bug BBQ 
> 
> I also miss information on the role of maintainers in the life cycle of a lesson. For instance I was not a maintainer when SWC moved from python 2  to python 3 but in general such evolution can happen and I don't really know how they are handled by the Carpentries. In addition, some lessons (such as Data Carpentry Geospatial) are not "mature" yet and still under development. It has an impact on the maintainer (both in terms on involvment and type of work).
> 
> Finally I miss a section for CONTRIBUTORS: I mean guidance for whoever wants to contribute to lessons (and submit issues or answer to existing issues), become an instructor, run workshops, become an instructor of instructors, etc.

**Comment by ErinBecker** [comment]
To do list: 

- [ ] Step for Maintainer Onboarding process
- [ ] Template emails
- [ ] Maintainer Onboarding lesson (https://carpentries.github.io/maintainer-onboarding/index.html)
- Maintainer operation i.e. day to day work with information such as: 
- [ ] How to deal with issues (most information is available in the Maintainer Onboarding lesson)
- [ ] How to label issues
- [ ] How to get help (slack, help-wanted label, etc.)
- [ ] How to update the lesson template style (something I have never done so I don't know anything about it)
- [ ] How to be kept informed (slack, maintainer meetings, lesson development)

**Comment by ErinBecker** [comment]
I've added some of this information about put in placeholders for the other two items in the checklist above. Will be adding the last bits of information at a later point.

**Comment by maneesha** [comment]
@ErinBecker   This is an old issue - it is still relevant?   For the two unchecked points:

- If the information about how to deal with issues is in the Maintainer onboarding, do we also want to have it in this handbook?  
- For the lesson template style, I know @fmichonneau  has been doing a lot of work on this.  François, do you have suggestions on what do include here?  I've updated things in the style repo but I don't know how to make those changes reach the lessons.

**Comment by maneesha** [comment]
Checking in @ErinBecker

**Comment by ErinBecker** [comment]
Yes - this is still super incomplete. Can you add to our agenda for tomorrow to plan out what needs to be done here?

**Comment by maneesha** [comment]
@fmichonneau  @ErinBecker  @tobyhodges  @zkamvar 
Is this something the curriculum team is still working on?

**Comment by tobyhodges** [comment]
@maneesha This is a topic of active discussion among the Maintainers at the moment, so this is not the right time to try to add this content. I have made a note to revisit this issue in early June.

**Comment by ErinBecker** [comment]
PR #735 addresses the fourth bullet point in the above checklist. @tobyhodges will be submitting another PR to address the remaining checklist item, after which point this issue can be closed.

**Comment by maneesha** [comment]
The final bullet is _How to update the lesson template style_

Is this something @zkamvar  could address?

**Comment by zkamvar** [comment]
I can address this. FWIW, this is one of those things that I didn't want to spend too much energy on because the changes in the new lesson infrastructure will remove the need for this process.

**Comment by maneesha** [comment]
@zkamvar  I'm OK deferring this if you think it will soon be irrelevant.

**Comment by maneesha** [comment]
Pinging @zkamvar 
*How to update the lesson template style* is the only item on this list. You noted it will soon be irrelevant. Can we close this?

**Comment by maneesha** [comment]
@tobyhodges  @zkamvar  can we close this as outdated?

**Comment by maneesha** [comment]
@tobyhodges I'd like to close this as outdated - please let me know if there is anything here that still needs attention.
