### ISSUE TITLE
Missing checkout instructions on issues/pull requests

### ISSUE THREAD

**Issue by Denubis** [carpentries/docs.carpentries.org#489]
This repo doesn't have the contribution pro-forma in the pull request text:

Please delete this line and the text below before submitting your contribution.

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

If this issue is about a specific episode within a lesson, please provide its link or filename.

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at team@carpentries.org.

**Comment by maneesha** [comment]
Thanks @Denubis 
The language you've quoted above is for our lesson repos.  We don't have it here as this repo is not part of the lesson maintainers or checkout process.  

Please feel free to re-open if you still think it would be useful to have some type of default text here or on the many other non-lesson repos within The Carpentries.

**Comment by Denubis** [comment]
Hi @maneesha 

@jduckles and I made a point of saying that any pull request on an actively maintained repo in the carpentries orgs would be valid for checkout. Looking at https://carpentries.github.io/instructor-training/20-checkout/index.html#lesson-contribution it does say "Lesson" rather than "carpentries repo" 

Looking at https://carpentries.github.io/instructor-training/checkout/ does indicate that we were simply wrong. Maybe a proforma saying "If you wish to check out, make sure you're contributing to a lesson in 'this list' " 

Sorry to have been a bother.

**Comment by ErinBecker** [comment]
We actually do accept any issue, comment, or PR to any actively maintained repo in the carpentries org (or swc, dc, or lc orgs) as valid for checkout. Not a bother at all - @maneesha can make sure this information is updated. Thank you!

**Comment by maneesha** [comment]
Thanks for this update @ErinBecker 
I wasn't aware of that.  I'm putting in an issue in the [instructor training](https://github.com/carpentries/instructor-training/issues/1024) repo to consider updating the checkout instructions, which imply that contributions are meant for lessons.

I'm also making a note to myself to update the default text across all actively maintained repos in The Carpentries and its three lesson programs.

**Comment by maneesha** [comment]
I will be bringing this up again with the instructor training team so that we are clearly and consistently communicating about what repos trainees can contribute to.

**Comment by maneesha** [comment]
Closing this due to upcoming changes in IT checkout requirements.
