### ISSUE TITLE
Section in carpentries-es not translated

### ISSUE THREAD

**Issue by maneesha** [carpentries/docs.carpentries.org#493]
The [carpentries-es](https://docs.carpentries.org/topic_folders/regional_communities/carpentries_en_latinoamerica.html#) section includes English and Spanish translations of all sections except [Como puedes ayudar/ways to help](https://docs.carpentries.org/topic_folders/regional_communities/carpentries_en_latinoamerica.html#como-puedes-ayudar-ways-to-help).

Anyone interested in helping with this translation?  @raynamharris @orchid00 @smcclatchy ?

**Comment by raynamharris** [comment]
I can work on this

**Comment by maneesha** [comment]
Thanks Rayna!

**Comment by maneesha** [comment]
Trying to clear out some old issues....
I know Rayna has stepped back from Carpentries related work.   @orchid00 @smcclatchy would you be interested in translating  these few bullet points?

**Comment by yabellini** [comment]
Hay muchas formas de ayudar a construir la comunidad de _Carpentries_ en América Latina.

    * Necesitamos hablantes nativos y con fluidez de español para ayudar a traducir los materiales de las lecciones.

    * Necesitamos una forma de mantener sincronizadas las diferentes versiones de idiomas de las lecciones de The Carpentries para que las contribuciones hechas a una versión también aparezcan en otras versiones.

    * Necesitamos instructores experimentados para enseñar y guiar a los nuevos instructores en América Latina, especialmente aquellos familiarizados con la región.

    * Necesitamos Capacitadores ubicados en América Latina o con fuertes vínculos con la región.

    * Necesitamos ayuda con la coordinación de talleres de personas familiarizadas con las estructuras de precios, la geografía y la infraestructura computacional en América Latina.

    * Necesitamos campeones locales para correr la voz sobre The Carpentries y el trabajo que hacemos y abogar por los talleres y membresías de The Carpentries en la región.

Si puede ayudar de alguna de estas formas, o conoce otra forma en la que pueda apoyar el desarrollo de la comunidad de The Carpentries en América Latina, ¡póngase en contacto a través de la lista de correo!

**Comment by maneesha** [comment]
This is amazing -- thank you @yabellini!!

My Spanish is not so good but I wanted to double check one point:

Necesitamos una forma de mantener sincronizadas las diferentes versiones de idiomas de las lecciones de The Carpentries para que las contribuciones hechas a una versión aparezcan en los otros idiomas.

should be

Necesitamos una forma de mantener sincronizadas las diferentes versiones de idiomas de las lecciones de The Carpentries para que las contribuciones hechas a una versión aparezcan en los otros versións.

Is that right?

**Comment by yabellini** [comment]
Almost!

_Necesitamos una forma de mantener sincronizadas las diferentes versiones de idiomas de las lecciones de The Carpentries para que las contribuciones hechas a una versión aparezcan en las otras versiones._

**Comment by maneesha** [comment]
Fixed with #721
