### ISSUE TITLE
[Translations] - md links do not appear. Suggesting change to reST 

### ISSUE THREAD

**Issue by dpshelio** [carpentries/docs.carpentries.org#506]
I imagine we've been using a mix of md and reST files because md is easier and allows more people to get on board editing the files. However, I'm finding a big blocker. When translating documents the gettext tools provided by sphinx-intl removes the links from the text, therefore making the translations not as rich as they should be. For example, see one of the translated pages already:

[English](https://carpentrieshandbook.readthedocs.io/en/latest/topic_folders/policies/incident-reporting.html) vs [Spanish](https://carpentrieshandbook.readthedocs.io/es/latest/topic_folders/policies/incident-reporting.html)

As you can see, there's a lot of links lost on the way. I've reported this issue to what I think is the source - readthedocs/recommonmark#169

I've been trying to find a solution the whole day, and I'm giving up. Updating the whole repo to reST and produce the tokens with the appropriate links has taken me almost no time (#505). Therefore, I'd like to suggest to update the documentation to use only a single format, reST, avoiding fragiles elements (like [md tables](https://github.com/readthedocs/recommonmark/issues/103#issuecomment-459989918) or lost links). Github also renders reST format and the possibilites provided by this format are superior than md.

**Comment by maneesha** [comment]
Thanks for this suggestion @dpshelio  and for PRs #504 and #505 - I appreciate the time you've put in to this.  You're right that we mainly use `md` files because they're easier, and preferable from an inclusivity standpoint.  I think the TOC pages had to be in `rst` though; hence the inconsistency.   However, allowing ease of translation is also important to inclusivity so we want to consider this.  

We'll take a look at this more internally to see what would make sense on our end.

**Comment by maneesha** [comment]
Also - we've found sometimes link formatting gets tricky.  I added in some notes in the readme about this: https://github.com/carpentries/handbook#formatting-hyperlinks

**Comment by maneesha** [comment]
Closing this as I don't think we're ready to address this now; we can revisit it if we need to again.

**Comment by dpshelio** [comment]
What do we mean with not ready to address it? #505 is a way to convert all the documents into ReST. Should I keep a fork of the documentation all in ReST so the translations are richer?
Also, closing an issue while still is an issue is not a good practice. I would like to suggest the use of a label instead or milestones as to when this would be revisited. Otherwise, if it depends just on me, it will probably fall into oblivion.

**Comment by maneesha** [comment]
Hi @dpshelio  - thanks for your response.  First, I want to apologize to you.  I've had issues or PRs I've submitted simply closed, and it is a terrible feeling.  I am really sorry I made you feel that way.

I'm glad to see Erin has re-opened this.  As we look at how we manage translations of our resources, we do want to keep this as an option.  Thanks so much for what you've contributed so far.

**Comment by dpshelio** [comment]
Thanks @maneesha, it's OK. Don't need to apologise. I didn't feel terrible, I was trying to know whether there's been some discussion/decission that I had missed.

**Comment by astrojuanlu** [comment]
Hi! The recommonmark maintainers recently proposed to sunset it in favor of MyST-Parser, a better supported alternative https://github.com/readthedocs/recommonmark/issues/221

I saw @dpshelio mentioning the internationalization problems in several places (also in https://github.com/carpentries-i18n/i18n/issues/20). I would love to understand better how this is handled with MyST-Parser (although I suspect it's still not perfect, see [this comment](https://github.com/readthedocs/recommonmark/issues/221#issuecomment-822413448)) and find a solution. How can I help?

_Disclaimer: I recently started as Developer Advocate at Read the Docs, and one of my objectives is to make Markdown-on-Sphinx users happy!_

**Comment by maneesha** [comment]
Closing this because we will be transitioning to an [entirely new handbook](https://github.com/carpentries/handbook-beta), and we are building all pages in rst instead of md as it offers much more robust options.  We will not spend time translating the current handbook.

**Comment by astrojuanlu** [comment]
Hi @maneesha, thanks for keeping us posted. Two years have passed and MyST is much more robust now, and it's used extensively by adjacent projects like Executable Books, Curvenote and such. It has all the features reST has (roles, directives, cross-references, extensibility), while addressing some long-standing reST pain points that seemingly will never be addressed (like nested markup!) and having the advantage of being a CommonMark (standardized Markdown) dialect, hence "everybody knows it". I will not be participating writing the book but wanted to bring this up in case these factors were not considered.

https://myst-parser.readthedocs.io/

In any case, it's never too late to reconsider, rst-to-myst works like a charm https://github.com/executablebooks/rst-to-myst

Best luck!
