### ISSUE TITLE
Questions about the Style Guide

### ISSUE THREAD

**Issue by ppival** [carpentries/docs.carpentries.org#514]
In working through the [Style Guide](https://github.com/carpentries/handbook/blob/master/topic_folders/communications/resources/style-guide.md) the other day, I came away with the following questions:

- Under bullet points, does this same information apply to numbered lists as well? I think it should... (requires a new section)
- One or two spaces after periods? I *think* the world has decided that only one is necessary, but I guess clarification couldn't hurt...
- **e.g.** and **etc.** have entries, could we have one for **i.e.** as well? I think it would simply state that it always includes full stops - does it also always have a comma?

**Comment by kmomar** [comment]
Adding myself as an assignee and noting that I agree with all of these additions.

**Comment by kmomar** [comment]
@serahrono I looked into it and it seems i.e. does not have a comma after the full stop in British English, so I am going to proceed with codifying these entries.
