### ISSUE TITLE
Self-organised workshops should reflect new registration form instructions

### ISSUE THREAD

**Issue by iamc** [carpentries/docs.carpentries.org#521]
The new [self-organised workshop setup form](https://amy.carpentries.org/forms/self-organised/) states that you should

> fill out this form if you are a Carpentries Instructor or affiliated with a Member Organisation to register a self-organised workshop

which contradicts the handbook in several places, at least [here](https://docs.carpentries.org/topic_folders/workshop_administration/workshop_admin_workflow.html#for-self-organised-workshops), and [here](https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html#host-checklist).

**Comment by maneesha** [comment]
Thanks for bringing this up, @iamc .
Could you identify the specific points of discrepancy?

**Comment by iamc** [comment]
In [Docs » WORKSHOP ADMINISTRATION » Workshop Administration Workflow » For Self-Organised Workshops](https://docs.carpentries.org/topic_folders/workshop_administration/workshop_admin_workflow.html#for-self-organised-workshops) (this should be a bit different once my PR #517 is shown in the rendered version, but wrong in any case:

> Instructors notify Regional Coordinator about upcoming self organised workshop. This is no fee (suggested or mandated) for a self organised workshop.

and in [Docs » TEACHING AND HOSTING » Workshop Checklists](https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html#workshop-checklists) the host and instructors checklist should be adapted to show that the host fills the form just in case of a centrally organised workshop. 

Should you prefer to wait ~5 days, I'll generate a PR then.

**Comment by maneesha** [comment]
Hey @iamc  - Apologies for the delay in following up. We changed all our workshop request and self organized workshop forms a few weeks ago and I wanted to be sure that was all in place before making any changes.  If you're still interested in submitting a PR I'd be happy to review it for merging.  No obligation though - let me know!

**Comment by iamc** [comment]
Hi @maneesha, my fault, sorry. I didn't forget this, just a bit busy on my side. Give me a few days and I'll review this and submit a PR.

**Comment by maneesha** [comment]
Cleaning up some old issues. I think this has been fixed. @iamc  Please feel free to re-open if you still see anything wrong.
