### ISSUE TITLE
Teaching demo workflow should be more easily searchable

### ISSUE THREAD

**Issue by Denubis** [carpentries/docs.carpentries.org#522]
Ran a teaching demo this morning and was furiously looking around for https://docs.carpentries.org/topic_folders/instructor_training/trainers_guide.html?highlight=teaching%20demo#running-a-teaching-demonstration

Typing "teaching demo" into search doesn't have the parent above the fold:

![Screenshot from 2019-09-19 13-01-20](https://user-images.githubusercontent.com/243503/65210161-a60ce000-dadd-11e9-84fa-0bd4870d1a52.png)

And it takes a little bit of thought before realising that the link to the trainers guide is the correct link. One fix might be to have h3 headers show in search results.

**Comment by Denubis** [comment]
Besides reconsidering the hierarchy-level of headers, or making a "frequently accessed pages" FAQ style linking document, it looks like we'll need to adjust the level of header articulated by the full text search. I'll... try to figure out how to do that this weekend.

**Comment by maneesha** [comment]
Hey @Denubis I'm trying to clean out some of our super-old issues here.  The hierarchy not showing up in the search results is a limitation/feature of the template we use and I'm not sure that's something we can realistically fix now. If you do have suggestions though, I would welcome them! Otherwise I'd like to close this issue.

**Comment by Denubis** [comment]
While it'd be nice to have, just spent 15 minutes looking over the documentation and couldn't see anything trivial. Any changes would be significant and considering that no-one else is complaining about hard-to-find things, I'll close this.

(I do think an FAQ would be very useful, but that's also effort).
