### ISSUE TITLE
Add Grants as a tag for blog posts

### ISSUE THREAD

**Issue by serahrono** [carpentries/docs.carpentries.org#541]

**Comment by maneesha** [comment]
@kmomar @acrall We have a number of issues about tags on blog post that have been open for up to two years. Do you want to keep these open?

**Comment by kmomar** [comment]
@maneesha @acrall and I will work on this and other blog post tag issues on the next R&R Day

**Comment by kmomar** [comment]
Grants is a tag on our blog
