### ISSUE TITLE
Linking to Online Workshops Resources page prominently

### ISSUE THREAD

**Issue by serahrono** [carpentries/docs.carpentries.org#580]
Per @elletjies' great suggestion to help people quickly find the Online Workshops Resources page over the next few months while they are figuring this out, we placed a link to the resource more prominently in the Handbook menu - right under the CoC link.

Keen to hear what your thoughts and suggestions around this are @maneesha @sheraaronhurt

**Comment by sheraaronhurt** [comment]
Thanks @serahrono . I agree with @maneesha  my recommendation was for this page to go under Teaching and Hosting a workshop. 

While I understand people want to quickly find the resources, I believe there are other resources that are under "Teaching and Hosting" that are useful as well for all Carpentries workshops. ie email templates. 

I would like for everyone to be guided to this page that way if we decide to keep online workshops, Instructors will know where to go.

**Comment by maneesha** [comment]
As I noted in #576  I thought that putting it immediately below the COC is actually too prominent, and implies that online workshops are an expected norm.  

It seems that @sheraaronhurt  also agrees, and would like to see this in the Teaching and Hosting section.  I'll work on making that change.

**Comment by serahrono** [comment]
thanks @maneesha and @sheraaronhurt. Noting that the page is already under the teaching and hosting section - see  https://docs.carpentries.org/topic_folders/hosts_instructors/resources_for_online_workshops.html

adding @elletjies to this conversation as this is an idea she raised, and made good points for in our Community Development Team meeting a week ago. She is off till Monday, May 4, please wait for her input before making any changes. Thanks both.

**Comment by elletjies** [comment]
Thanks @serahrono for bringing me into this conversation. @maneesha and @sheraaronhurt, just a bit of background,  The Carpentries Handbook might be a bit difficult to navigate (particularly to novice instructors). So my suggestion was that we place the Resources for Online workshop page prominently for easy access. However, I do understand separating these two resources might not make sense at all. Suggestion, how about adding the Resource to online workshops to the Teaching and Hosting section, but then moving this up below the CoC?

**Comment by serahrono** [comment]
Ola @elletjies @maneesha and @sheraaronhurt cc @fmichonneau 

having thought about the points raised in this conversation, and those in https://github.com/carpentries/carpentries.org/issues/745, here's a proposal on the way forward:

- have the  https://docs.carpentries.org/topic_folders/hosts_instructors/resources_for_online_workshops.html page under the Teaching and Hosting section in the Handbook, and remove its prominent placement under CoC. 
- on the homepage of our website, carpentries.org, create a new section right above the Upcoming Workshops section and add a blurb about the official recommendations page on the left half, and a blurb about the aggregated resources page on the right half.

If everyone is on board with this idea, I will go ahead and add a PR for this.

**Comment by elletjies** [comment]
This sounds good and easily accessible to instructors (new and old).

**Comment by maneesha** [comment]
I like this idea.

**Comment by sheraaronhurt** [comment]
This is great!
