### ISSUE TITLE
consolidate page for online workshop resources

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/docs.carpentries.org#584]
this link:  https://docs.carpentries.org/topic_folders/hosts_instructors/index_online.html brings up a table of content where all the elements belong to the same page (https://docs.carpentries.org/topic_folders/hosts_instructors/resources_for_online_workshops.html). Could we combine these pages into one (table of content at the top, content of the page below) or is there a reason to break it down this way?

**Comment by maneesha** [comment]
@serahrono  is working on a PR for #580 that I think should address this.

**Comment by serahrono** [comment]
this is now done @fmichonneau - Page is here https://docs.carpentries.org/topic_folders/hosts_instructors/resources_for_online_workshops.html

**Comment by maneesha** [comment]
Thanks @serahrono ! Closing.
