### ISSUE TITLE
update jQuery

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/docs.carpentries.org#591]
make sure we upgrade jQuery (it looks like it's being used by the theme, and inline for showing the Google calendar in the correct time zone).

**Comment by maneesha** [comment]
Thanks @fmichonneau 
I can update what's used for the calendar time zone.

I'm not sure how to update the theme though.

**Comment by maneesha** [comment]
#601 removes jquery from the calendar view.

As discussed with @fmichonneau this week, jquery is loaded by the site theme so we will wait until the theme is updated.

**Comment by fmichonneau** [comment]
I opened https://github.com/sphinx-doc/sphinx/issues/7696 to report the need to upgrade on the sphinx template.

**Comment by maneesha** [comment]
@fmichonneau  It looks like the theme has been updated. Is this OK to close?

**Comment by maneesha** [comment]
It was called in one more place as we recently added in another calendar view.  #636  takes care of that.

**Comment by fmichonneau** [comment]
thanks Maneesha!
