### ISSUE TITLE
Separate community-facing from core-team-facing Zoom/calendar instructions?

### ISSUE THREAD

**Issue by karenword** [carpentries/docs.carpentries.org#596]
I was reviewing the new Zoom instructions [here](https://docs.carpentries.org/topic_folders/communications/tools/zoom_rooms.html?highlight=zoom#adding-an-event-to-the-community-calendar) (yay!) and strayed into the room scheduling text below when scrolling down. There are repeated paragraphs stating that community members can't do this, but I had to look for those because I knew they should be there. 

I think with the increased traffic on the Zoom instructions page it might be better to separate these, as we do for email templates, into 'for the community' and for admins' sections.

**Comment by maneesha** [comment]
Great idea. I will work on separating this out.

**Comment by maneesha** [comment]
Fixed with #600
