### ISSUE TITLE
Process Flow Diagram for Code of Conduct

### ISSUE THREAD

**Issue by annajiat** [carpentries/docs.carpentries.org#619]
Hi, 

Can we have a visual representation of code of conduct related procedures?

A Process Flow Diagram could be a great addition for easier comprehension to the summary view at
https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#code-of-conduct-summary-view

Best regards,
annajiat

**Comment by maneesha** [comment]
Thanks for bringing this up @annajiat 

I'm referring this to the @carpentries/code-of-conduct-committee for follow up. Is a flow chart something you would be able to create for inclusion in the handbook?

**Comment by annajiat** [comment]
1. This is something that would help community members comprehend
- overall process
- sub processes  
It short, it would be a pictorial summary of existing list items.

2. I would be happy to create given some directions and guidance.

**Comment by maneesha** [comment]
Pinging  @carpentries/code-of-conduct-committee -- any thoughts on this?

**Comment by karinlag** [comment]
I see this is still open. Question: is it how the process looks like from outside, or what goes on internally you are looking for? The two naturally overlap but the internal one is considerably more convoluted :)

**Comment by annajiat** [comment]
Primarily, how the process looks like from outside for the general members
and then later if possible, internal one for the people aspiring to be a part of the CoC team

**Comment by malvikasharan** [comment]
Hi Annajiat, we are in the process of finalizing the committee structure (that Karin has worked significantly on) - one that is approved, we will add that to the CoC documents. If you are considering to join the committee, you should have a look at this document for now: https://docs.carpentries.org/topic_folders/policies/coc-membership-agreement.html (and really sorry for the late reply, I did not see this before Karin replied here.)

**Comment by karinlag** [comment]
I think an "outside" view can be put together quite easily. @malvikasharan, I will contact you directly and we can see what we can do.

**Comment by annajiat** [comment]
@malvikasharan 
I am interested in joining the committee.
I have read https://docs.carpentries.org/topic_folders/policies/coc-membership-agreement.html
Is there anything else that I should do for now?

**Comment by maneesha** [comment]
Checking in with  @carpentries/code-of-conduct-committee and @fmichonneau  as the Core Team liaison.  Is this something you'd still like to consider, or can we close this?

**Comment by maneesha** [comment]
Ping @carpentries/code-of-conduct-committee and @fmichonneau as the Core Team liaison.

**Comment by malvikasharan** [comment]
Hi @maneesha, we have received @annajiat's application :) My apology that we missed this thread.  

For future reference, @annajiat, we open call for applications periodically for volunteer members to express their interest to join. They are onboarded through training and induction to ensure they understand their roles and responsibilities. Part of that onboarding process is to have them read and agree with the membership agreement.

**Comment by maneesha** [comment]
Assigning this to @fmichonneau  as the Core Team Code of Conduct liaison.

**Comment by kariljordan** [comment]
@malvikasharan is the CoCc still considering creating a flowchart to explain the various processes, or can we close this? I will also ping the CoCc Slack.

**Comment by malvikasharan** [comment]
Hi all, we use a process diagram internally, which builds off the . Here is a screengrab provided by @karinlag. This is not screenreader compatible format so providing a list of steps illustrated here: 
- First report -> assess if there is a CoC report and clear breach
  - No report or breach -> respond with an explanation to the reporter
  - Breach identified -> set up a first meeting with the CoCc (Read about Incident Response Group in CoCc Governance) to collectively identify specific issues and breaches
- If a specific breach/issue was not identified -> reply to the reporter
- If a specific breach/issue was identified -> email the reporter and/reportee as explained in CoC report handling and enforcement process
- If it was undecided that a breach/issue occurred -> hold a meeting with the Reporter/Reportee as explained in CoC report handling and enforcement process -> Hold a second meeting with the CoCc to identify consequence/next steps as explained in CoC report handling and enforcement process

<img width="720" alt="image" src="https://user-images.githubusercontent.com/5370471/211379997-67326f96-1b21-4acf-bca8-7e995491e4d5.png">

**Comment by kariljordan** [comment]
Thank you, @malvikasharan, for providing this diagram.

@maneesha is there a way to include this in the appropriate spot in the handbook?
