### ISSUE TITLE
Zoom instructions for sharing computer audio (for Trainers)

### ISSUE THREAD

**Issue by karenword** [carpentries/docs.carpentries.org#635]
In a recent workshop, my co-Trainer had difficulty showing the example videos because the audio did not play correctly through Zoom. Since then, I noticed that the screenshare selection window has a checkbox for "use computer audio" and I suspect this might have solved the problem.

Currently the "screen sharing" [section](https://docs.carpentries.org/topic_folders/communications/tools/zoom_rooms.html?highlight=zoom#screen-sharing)  mostly targets determining who can screen share but seems to be the best place for this addition. 

Filing this as an issue rather than a PR because I'm not 100% sure that this would have solved our problem, or that this is the right place to add this advice. :)

**Comment by maneesha** [comment]
We just tested this out.  Instructions should remind people to select the "Share Computer Sound" option if they want audio from a video to play.
