### ISSUE TITLE
Workshop survey instructions out of date

### ISSUE THREAD

**Issue by maneesha** [carpentries/docs.carpentries.org#641]
The Handbook still refers to setting up survey instructions via Survey Monkey.  
@Talishask  am I right that we are using Typeform and the app to send surveys for ALL workshops?  That would mean this section should be removed.  Talisha, do you have recommendations on what this section should say instead? 

Link to the section I'm talking about: https://docs.carpentries.org/topic_folders/workshop_administration/survey_monkey.html

**Comment by maneesha** [comment]
We would also need to change the instructions to set up Survey Monkey on these checklists: https://docs.carpentries.org/topic_folders/workshop_administration/workshop_admin_workflow.html#for-self-organised-workshops

**Comment by Talishask** [comment]
Hey @maneesha, Yes you are correct about survey monkey (SM). We are using typeform for all workshop surveys and using SM only for training surveys. A good temporary solution until we've completed our automation and infrastructure updates would be to remove the section linked here: [https://docs.carpentries.org/topic_folders/workshop_administration/survey_monkey.html](https://docs.carpentries.org/topic_folders/workshop_administration/survey_monkey.html)

and then update the working in the [checklist](https://docs.carpentries.org/topic_folders/workshop_administration/workshop_admin_workflow.html#for-self-organised-workshops)to:
5. The Workshop Administration Team will share a link to view the survey results with hosts and instructors via email. The survey result link is for instructors/hosts and should not be shared publicly. _As a reminder, learner facing survey links are automatically generated on the workshop's GitHub webpage._

Let me know if there are any questions. - Talisha

**Comment by maneesha** [comment]
Closing, fixed with #647
