### ISSUE TITLE
Can Zoom calendar display UTC and local?

### ISSUE THREAD

**Issue by karenword** [carpentries/docs.carpentries.org#667]
Referring to calendar here: https://docs.carpentries.org/topic_folders/communications/tools/zoom_rooms.html#viewing-zoom-room-availability

In my own Google Calendar, I am able to display two time zones. Since all our events are listed in UTC, I think it would be particularly useful to have this feature available on this calendar if possible -- this way the participant can double check the UTC time against that listed elsewhere and also see the event in their own time zone.

**Comment by maneesha** [comment]
This is a feature that can be enabled in a user's own calendar but not in the view that's embedded in a page like this.  It's a good idea but not something that we can implement in a practical way.
