### ISSUE TITLE
Add Committee and Task Force Policies to the handbook

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/docs.carpentries.org#675]
The Executive Council recently approved the Committee Policy and Task Force Policy. We'd appreciate it if these texts can now be added to the Handbook, so we can link to them from the Bylaws.

* [Committee Policy](https://docs.google.com/document/d/1UEGzYNl_Mz3oz_j_Hk6NK7_BaZ5rZw8B9YYw8b_PoEY/edit)
* [Task Force Policy](https://docs.google.com/document/d/1hnxSk1d-rmjZjS5ndJm2ZiHdf2eBRxCgEYa9PiPZoiY/edit)

**Comment by maneesha** [comment]
Thanks @lexnederbragt 
I'll work on getting these in the Handbook this week. Can you update the date on the bottom of the Committee Policy Document?

**Comment by maneesha** [comment]
Also @lexnederbragt  would you like to remove https://docs.carpentries.org/topic_folders/governance/committee-guidelines.html once the new Committee Policy page is up?

**Comment by lexnederbragt** [comment]
Thanks, @maneesha! Date updated.

**Comment by maneesha** [comment]
Fixed with #676 #677  #678
