### ISSUE TITLE
Add instructions for Zoom live captioning to handbook

### ISSUE THREAD

**Issue by kariljordan** [carpentries/docs.carpentries.org#686]
Thank you for providing such thorough instructions on [how to utilise Zoom for community meetings](https://docs.carpentries.org/topic_folders/communications/tools/zoom_rooms.html?highlight=zoom). In several upcoming workshops, the host will provide an individual to do live captioning for these events. I believe live captioning is already enabled on our Zoom rooms, but we do not have instructions for what the host should do to assign a captioner in a Zoom meeting. Can these instructions be added to [this page](https://docs.carpentries.org/topic_folders/communications/tools/zoom_rooms.html?highlight=zoom)? Here is a [short video](https://support.zoom.us/hc/en-us/articles/207279736-closed-captioning) on managing and viewing closed captioning with Zoom.

**Comment by maneesha** [comment]
See draft PR #688 in progress.
