### ISSUE TITLE
Feedback on the Committee and Task Force Policies

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/docs.carpentries.org#700]
This issue is for the community, and especially Committee and Task Force members, to give feedback on the recently adopted [Committee Policy](https://docs.carpentries.org/topic_folders/governance/committee-policy.html) and and [Task Force Policy](https://docs.carpentries.org/topic_folders/governance/task-force-policy.html). Please add any feedback you may have as a new comment.

**Comment by Al-Obayuwana** [comment]
Committee policy add something around sharing positive stories "bright spots" with broader community, remembering their lens. Task force, I would suggest this be used for short term items, 3 months 6 max. Focus on info gathering for another decision or challenge.

**Comment by ErinBecker** [comment]
My questions are with respect to the Curriculum Advisory Committees (currently inactive) and Maintainers. 

## Maintainers 
- Are they a committee? My instinct is that they aren't as they are a very large group (>80). They do, however, already fulfill the vast majority of the committee requirements. Could I get a ruling on this one please to see whether this group will be treated as a committee?

## [Curriculum Advisory Committees (CACs)](https://docs.carpentries.org/topic_folders/lesson_development/lesson_development_roles.html#curriculum-advisory-committee)
- CACs are currently inactive, but in the past have included separate committees for SWC, DC Genomics, DC Geospatial, and DC Social Sciences.
- When/if these CACs are reconvened (and new ones are formed) I believe they will count as committees and be subject to these policies. As such, I would like to note that CACs have historically met 2x per year (not the minimum of 4 in the policy). I'd like to request that for these groups, 2 meetings per year be sufficient and written updates to EC once per year. I would also like to request that they not be required to host a community discussion.

**Comment by tobyhodges** [comment]
- In my experience, there is often confusion about the difference between a committee and a task force. I recommend linking to the descriptions in https://docs.carpentries.org/topic_folders/governance/bylaws.html#committees-and-task-forces early in each page. (Happy to make a PR to this effect.)
- what (if any) are the other ways a committee can be terminated? e.g. can the committee members submit a proposal to the EC that the committee be dissolved? (I know that, technically, this would still mean the EC is determining that the committee be dissolved, but it feels important that the more bottom-up approach be mentioned in the policy too.)
- I like [the Task Force Charter template](https://github.com/carpentries/task-forces/blob/master/task-force-charter-template.md), and think the Committee Policy would benefit from a little more detail about what should be included in the "short description of what the committee does." In particular, I think it would be important for the scope of the committee to be properly defined - what decisions does the committee have the power to make?
- "Task Force" is written with and without an initial uppercase throughout the Task Force Policy page. If you can tell me whether it should be "Task Force" or "task force" I will be happy to submit the pull request to make this consistent.

**Comment by kariljordan** [comment]
The EC’s decision-making transparency led to a change in the [Committee Policy (in Handbook)](https://docs.carpentries.org/topic_folders/governance/committee-policy.html) where the EC no longer needs to approve all committees. The handbook will be updated to reflect this information. 

@anenadic there are still unanswered questions in this issue from @ErinBecker and Toby (who is on leave at the moment). Can you take these questions to the Program Committee of the EC?

**Comment by anenadic** [comment]
Hi @kariljordan, the Program Committee of the EC discussed this at our last meeting (see https://github.com/carpentries-ec/conversations_ec_ed/issues/134) but I will make sure we go back and revisit comments from @ErinBecker and @tobyhodges.

**Comment by anenadic** [comment]
Update: I've just been in touch with the Program Committee - we agreed to readdress this at our next meeting unless this issue is urgent @kariljordan.

**Comment by kariljordan** [comment]
Thanks @anenadic! Not urgent. When you have updates please add them here and resolve the issue as needed.

**Comment by anenadic** [comment]
The work on this is on a branch in the Handbook repo: https://github.com/carpentries/docs.carpentries.org/tree/committees-task-forces-policies.

**Comment by kariljordan** [comment]
@anenadic since we are no longer collecting feedback and now have a pull request being drafted we can close this issue.
