### ISSUE TITLE
consider adding  accessibility checklists for online events

### ISSUE THREAD

**Issue by serahkiburu** [carpentries/docs.carpentries.org#701]
https://docs.carpentries.org/topic_folders/hosts_instructors/workshop_needs.html#accessibility primarily offers a checklist for in-person events

**Comment by maneesha** [comment]
Thanks for bringing this up @serahrono .  I see you assigned to yourself - Is this something you are working on? Do you need anything from other Core Team members?

**Comment by sheraaronhurt** [comment]
this is being addressed with POW. @danielle06 and I are working on a checklist for online workshops. Once it is complete, I can link here.

**Comment by maneesha** [comment]
Assigning this to @brynnelliott - not sure what your workflow or workload is like, so prioritize as you see fit

**Comment by sheraaronhurt** [comment]
Here is the checklist created for SOW: https://docs.google.com/document/d/19PTjQBp3JluTYi6rocxe0WYoG08taedanRRQhk_BDUs/edit

**Comment by maneesha** [comment]
@brynnelliott Cleaning up some old issues.  Does an accessibility checklist for workshops exist?

**Comment by brynnelliott** [comment]
@maneesha  We have two tip sheets, a more condensed version and one that explains why the tips are important. I will add them to the website now. Once its merged we can add those links. 

https://docs.google.com/document/d/1oa4i0Ef7fNPXsfEUQ3eeT_8PS_2N0t65Tb4ONWfV7qI/edit 
https://docs.google.com/document/d/1yZXIwtkaRfi2XGpXLOdaVfjzLgOrHyD33hqx8KyFqfM/edit

**Comment by maneesha** [comment]
@elletjies Is there a place we are linking these resources now? Can we close this issue?

**Comment by elletjies** [comment]
@maneesha the toolkit of ideas has checklists etc - it is available on Zenodo. I think we can close this issue.
