### ISSUE TITLE
improve content accessibility by expanding word contractions

### ISSUE THREAD

**Issue by serahkiburu** [carpentries/docs.carpentries.org#705]
Word contractions might make readability and comprehension more difficult for some, and it is best to avoid these. [This post provides more context around this](https://medium.com/@joanne.schofield/using-contractions-could-be-making-your-writing-inaccessible-4034bb3cd76a). 

We invite you to help us make our content more accessible by [creating Pull Requests](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) in this repository to  word contractions where relevant. If in doubt, please ask for clarification under this issue.

(not required but nice to have)Where possible, you can also [mention this issue in your Pull Request](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to enable us to keep track of accessibility improvements made on this specific issue.

Thank you for your contributions.

**Comment by maneesha** [comment]
Assigning this to @brynnelliott - not sure what your workflow or workload is like, so prioritize as you see fit

**Comment by maneesha** [comment]
Closed based on comment from @brynnelliott  here (https://github.com/carpentries/docs.carpentries.org/issues/702)
