### ISSUE TITLE
Add blog post templates / guiding questions

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/docs.carpentries.org#71]
[For after Instructor Training event](https://docs.google.com/document/d/1iJROM0QynqzCKFh2hEkjUYWsEttDTPbrFZz-xcTwbzo/edit)

[For Data from the Field](https://docs.google.com/document/d/1OYJ2N68uJrltc8VWcYGYqG34cUISxNs4wmZSmrIl1w8/edit)

I'm not sure if we're still running the "Data from the Field" series. @weaverbel

**Comment by maneesha** [comment]
@weaverbel I'll add in the ones @ErinBecker  already linked to. Let me know if you have templates/guides as well.

**Comment by maneesha** [comment]
@serahrono   This is something that we started working on as a way to encourage blog posts from our community.   Do you think we should pick this up again or can we close it for now?

**Comment by serahrono** [comment]
hey @maneesha, thanks for bringing this to my attention. Leave it open for now, we'll discuss it with the team and share an update here soon.

**Comment by maneesha** [comment]
Thanks @serahrono 
This is also connected to our conversations in Asana about the blogs.  Let me know if you think we should keep this open.

**Comment by maneesha** [comment]
Hi @serahrono  Given your recent restructuring of the Communications section of this handbook, do you still want to keep this open?

**Comment by maneesha** [comment]
@serahrono  and @kmomar Do you want to keep this open?

**Comment by maneesha** [comment]
@serahrono and @kmomar Do you want to keep this open?

**Comment by maneesha** [comment]
@acrall  and @kmomar Do you want to keep this open?

**Comment by kmomar** [comment]
@maneesha I think we can close it, but leave it up to @acrall for final decision

**Comment by kmomar** [comment]
@maneesha @acrall We discussed this and with the in-development community coordinator program, blog post templates are part of the onboarding, so we are closing this.
