### ISSUE TITLE
Consider modification to CoC with respect to the law in MENA

### ISSUE THREAD

**Issue by BatoolMM** [carpentries/docs.carpentries.org#722]
We wish to expand the Carpentries community in the Middle East and North Africa (MENA) region (e.g. Saudi Arabia). We believe it will largely benefit the academic institutions in Saudi Arabia and it is in line with [vision 2030](https://www.vision2030.gov.sa/en). However, there's some concern that few issues within CoC might possibly be raised as they might clash with the law in this region.  After a discussion with @serahrono about the CoC in [Open Life Science Program](https://github.com/open-life-science/ols-3/issues/39).  Serah recommended that I raise the issue here and will follow with it later.

**Comment by maneesha** [comment]
Thanks for bringing this up @BatoolMM 
I am not familiar with MENA.  Could you hare some more details about the law and how our CoC or other policies may conflict with it?

**Comment by BatoolMM** [comment]
Thank you @maneesha for your prompt reply. I'm happy to elaborate on this issue and follow on it later. I realise that what I've written above is extremely short and isn't descriptive but I only wanted to report the issue very briefly as I was asked after a meeting with @serahrono. Thak you again.

**Comment by maneesha** [comment]
Tagging @acrall  as our new CoC Core Team liaison.

**Comment by acrall** [comment]
Thanks, @maneesha, for ensuring this continues to be assigned to the new liaison. @BatoolMM Please let me know if you would like to find a time to connect on this, and I can bring it to the next CoC Committee meeting. I realize that the opening of this issue was some time ago and things may have shifted since then.

**Comment by maneesha** [comment]
@acrall  as the Core Team CoC liaison, would you like to still keep this open?

**Comment by BatoolMM** [comment]
Thank you all - I will close this issue for now, hope that's OK!
