### ISSUE TITLE
'vs' vs 'vs.'

### ISSUE THREAD

**Issue by gcapes** [carpentries/docs.carpentries.org#737]
There's a PR in the shell lesson suggesting changing the former to the latter. There's no entry in the style guide for clarification. I reckon 'vs' because the dot suggests missing letters. So you could have 'v.' but not 'vs.'. 

A decision one way or the other would be appreciated. Thanks!

**Comment by gdevenyi** [comment]
https://english.stackexchange.com/questions/52378/versus-versus-vs-in-writing

**Comment by gcapes** [comment]
https://www.onlinegrammar.com.au/the-grammar-factor-punctuation-with-abbreviations-collective-nouns-podcasts/

**Comment by kmomar** [comment]
Hello, I will add this to the style guide, but we are going to proceed with the following guidance: Use versus in most written cases, but if abbreviation is necessary, use "vs" 

Thank you for flagging this.

**Comment by gcapes** [comment]
Great, thanks!

**Comment by maneesha** [comment]
Thanks @kmomar  I've just assigned this to you

**Comment by kmomar** [comment]
fixed by #751
