### ISSUE TITLE
CoC needs admin support from staff liaison - update the policy doc after discussion

### ISSUE THREAD

**Issue by malvikasharan** [carpentries/docs.carpentries.org#741]
## Summary

CoC members need help in scheduling meetings, sending calendar invites, setting zoom link (carpentries room)

This might be a question for @fmichonneau as the CoC liaison, if we can update the role in the CoC governance doc

**Comment by kariljordan** [comment]
I am closing this issue as @acrall and I are currently supporting the CoCc. Alycia recently set up the CoCc business meeting taking place on 7 February, for example. @malvikasharan if there are other issues related to CoCc needs from the Core Team please email community@carpentries.org.
