### ISSUE TITLE
Add instructions on setting up and scheduling teaching demos

### ISSUE THREAD

**Issue by ha0ye** [carpentries/docs.carpentries.org#744]
Per @JCSzamosi, add instructions to `topic_folders/instructor_training/trainers_guide.md` on procedures for trainers on setting up and scheduling teaching demos.

**Comment by maneesha** [comment]
Thanks for bringing this up @ha0ye 
What specific information would be useful to include here that's not already in the handbook?

**Comment by karenword** [comment]
I don't think there is anything currently in the handbook about scheduling -- I was probably supposed to add this when we changed over to Calendly but never did :) We do have [a brief section about how workshops are scheduled](https://docs.carpentries.org/topic_folders/instructor_training/trainers_guide.html?highlight=demos#signing-up-to-teach-an-instructor-training-event), but I don't see anything on demos.

**Comment by maneesha** [comment]
This will be addressed with #799

**Comment by maneesha** [comment]
Resolved with #799 and #811
