### ISSUE TITLE
Did bullet points disappear?

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/docs.carpentries.org#754]
I have the impression that lists that used to be formatted with bullets are no longer having these bullets. Example: https://docs.carpentries.org/topic_folders/governance/executive-council.html has lots of lots with lines staring with `- ` in markdown, that do not have a bullet in front of them when I look at the rendered html in Safari (MacBook and iPhone) or Chrome (MacBook).

**Comment by maneesha** [comment]
I just tried this on a few OSs/browsers.  I see bullets on all of the below:

* Chrome (Linux/Ubuntu, Android, Mac)
* Safari (Mac)
* Firefox (Linux/Ubuntu)

@lexnederbragt  are you still having this issue? I'll keep this open a bit for others to note problems as well.  It may have just been a temporary glitch, in which case I'll close this.

**Comment by lexnederbragt** [comment]
Bullets are back for me too! Weird - but also great news I guess... For me this issue can be closed.
