### ISSUE TITLE
Include Bonus Modules in Professional Development for Instructors

### ISSUE THREAD

**Issue by maneesha** [carpentries/docs.carpentries.org#775]
We have a section in the handbook for [Professional Development for Instructors](https://docs.carpentries.org/topic_folders/for_instructors/current_instructors.html#professional-development-for-instructors).  

Can we include information on Bonus Modules here? 

(I feel like I asked this somewhere else but can't find it now!)

**Comment by maneesha** [comment]
Pinging @klbarnes20

**Comment by klbarnes20** [comment]
Sorry for missing this. I have proposed some text about bonus modules and requested review from you, @maneesha  and @karenword  #798

**Comment by maneesha** [comment]
Fixed with https://github.com/carpentries/docs.carpentries.org/pull/798
