### ISSUE TITLE
Community Discussions Workflow

### ISSUE THREAD

**Issue by elletjies** [carpentries/docs.carpentries.org#779]
@maneesha and @acrall looking at the current Scheduling Community Discussions page (https://docs.carpentries.org/topic_folders/instructor_development/community_discussions_workflow.html#scheduling-community-discussions) this information seems quite outdated. Since the up to date information is found here - https://docs.carpentries.org/topic_folders/instructor_development/community_discussions.html#signing-up-to-host-or-co-host-a-community-discussion, can we delete the "Scheduling Community Discussions" section?

**Comment by acrall** [comment]
Similar to the email template, I think this section can be removed from the handbook since it will now be managed internally by the CDT. Want to check with @maneesha before removing it though

**Comment by maneesha** [comment]
Yes, I think we can remove the  "Scheduling Community Discussions" section.
@elletjies  would you like to put in  a PR?

**Comment by elletjies** [comment]
Done - https://github.com/carpentries/docs.carpentries.org/pull/792

**Comment by maneesha** [comment]
Closed with #792
