### ISSUE TITLE
Email Template - sign up to host community discussion session

### ISSUE THREAD

**Issue by elletjies** [carpentries/docs.carpentries.org#780]
@acrall should we update the email tempalte verbiage here - https://docs.carpentries.org/topic_folders/instructor_development/community_discussions.html#call-for-instructors-to-instructor-development-committee

**Comment by acrall** [comment]
Perhaps we should remove the email template from the handbook since it will be transitioned from the IDC to the CDT. What are your thoughts?

**Comment by elletjies** [comment]
Yes, here is the PR for your review - https://github.com/carpentries/docs.carpentries.org/pull/793

**Comment by maneesha** [comment]
Closed with #793
