### ISSUE TITLE
New CoC training and onboarding document

### ISSUE THREAD

**Issue by malvikasharan** [carpentries/docs.carpentries.org#794]
# Summary

Add details on how we onboard and train CoC committee members

## Details

- Recently we have onboarded new members in the CoC committee (see the recent transparency report: https://github.com/carpentries/executive-council-info/pull/65)
- In their onboarding, we proposed to add a new CoC documents describing the following aspects:
  - Application and selection process for the new members
  - Training and Onboarding of new members
  - Limited incident response privileges for the newly onboarded committee members
  - Full membership to the committee
  - Offboarding or stepping down from the committee

## Location of the proposed changes
- The document should be added here: https://github.com/carpentries/docs.carpentries.org/tree/main/topic_folders/policies

## Who should be involved

All CoC committe members, specifically the newly onboarded members who can add details from their experience

**Comment by maneesha** [comment]
@malvikasharan  Could you share more specifically what you'd like to have included in the handbook? You can either add more details here or put in a PR directly.  Thank you!

**Comment by malvikasharan** [comment]
hi @maneesha, this issue is opened for the CoC committee to create these documents. Apology, there is no action on you for this.

**Comment by kariljordan** [comment]
@malvikasharan would you like someone from the Core Team to take a first pass at creating this documentation? If so, we need any documentation/resources that you have.

**Comment by kariljordan** [comment]
All of the CoCc documentation has been migrated to a newly developed handbook. The CoCc will work with @acrall and @kariljordan on training once we hear back about their first business meeting.
