### ISSUE TITLE
Typo in  docs.carpentries.org/topic_folders/instructor_training/email_templates_trainers.md 

### ISSUE THREAD

**Issue by hoytpr** [carpentries/docs.carpentries.org#800]
The line:

["The Science of Learning"]({{ page.training_site }}/files/papers/science-of-learning-2015.pdf)

under "Read the following" doesn't point to the science-of-learning-2015.pdf file. If I could have found the file I would have put in a PR.

**Comment by maneesha** [comment]
Hi @hoytpr The link should be https://carpentries.github.io/instructor-training/files/papers/science-of-learning-2015.pdf

Let me know if you want to put in a PR.

**Comment by maneesha** [comment]
This was already fixed with https://github.com/carpentries/docs.carpentries.org/pull/805
