### ISSUE TITLE
Rewording for Clarification in Code of Conduct Incident Response Guidelines: Immediate Response Checklist

### ISSUE THREAD

**Issue by eszkirp** [carpentries/docs.carpentries.org#808]
Area for possible rewording for clarification within Code of Conduct Incident Response Guidelines < Immediate Response Checklist:

**In-Person Event Checklist (Carpentries Workshops, CarpentryCon, CarpentryConnect, Carpentries Instructor Training)**

- Ensure participants are safe.
- If not, refer to the Immediate Response Checklist.

"If not..." listed as separate bullet point, but is unclear in the scope of the section. Iterating, "If participants are not safe..." would be helpful for comprehension.

Link: https://docs.carpentries.org/topic_folders/policies/incident-response.html#checklists-for-responding-to-an-incident

**Comment by maneesha** [comment]
Thanks for this suggestion, @eszkirp 

I'm tagging @fmichonneau  (as our Core Team Coc Liaison) and @carpentries/code-of-conduct-committee for review.

**Comment by malvikasharan** [comment]
hi @eszkirp, thanks for pointing that out. Can you please make a Pull Request for that? Happy to do that if you prefer.
