### ISSUE TITLE
Update brand colours in handbook to make description easier to read

### ISSUE THREAD

**Issue by acrall** [carpentries/docs.carpentries.org#840]
@kmomar With the [new brand colours in the handbook](https://docs.carpentries.org/topic_folders/communications/resources/brand_identity.html), there are some that have descriptions that are difficult to read because the color is so light (e.g., Dew: #F5F8FF or rgb(245, 248, 255). I think updating all the descriptions to use the color black should fix this?

**Comment by zkamvar** [comment]
Instead of setting the text colour to black, we can add a `background-color: black` to the span elements.

**Comment by kmomar** [comment]
@zkamvar Ah yes! Let's do this.
