### ISSUE TITLE
Add entry to style guide about using jargon

### ISSUE THREAD

**Issue by maneesha** [carpentries/docs.carpentries.org#852]
See [this PR](https://github.com/carpentries/carpentries.org/pull/1440) where @brynnelliott replaces "tl;dr" with "Summary."

Brynn - please share any suggestions about how to best express this in our [Style Guide](https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html#)

**Comment by maneesha** [comment]
Bump @brynnelliott

**Comment by brynnelliott** [comment]
@maneesha I added this to the style guide and submitted a pull request.
