### ISSUE TITLE
CoC checklists should incorporate online workshops

### ISSUE THREAD

**Issue by karenword** [carpentries/docs.carpentries.org#867]
Currently the Code of Conduct content includes checklists for in-person and online events. However, workshops are included only under "in-person" events. This seems like a simple correction, but the checklist for in-person events actually seems more appropriate to online workshops than the list for online events, so I'm not exactly sure how this would best be corrected.

> In-Person Event Checklist (Carpentries Workshops, CarpentryCon, CarpentryConnect, Carpentries Instructor Training)

- > Ensure participants are safe.
- > If participants are not safe, refer to the [Immediate Response Checklist](https://github.com/carpentries/docs.carpentries.org/issues/new#checklists-for-responding-to-an-incident).
- > Listen to the reporter and write down as many details as possible.
- > Ask the reporter to report the incident via the [Code of Conduct Incident Report Form](https://goo.gl/forms/KoUfO53Za3apOuOK2). If they would rather you complete the report, complete the report with their assistance.
- > Inform the workshop host that there was an incident and that a report was submitted via the [incident report form](https://goo.gl/forms/KoUfO53Za3apOuOK2). If the incident involves the workshop host, report the incident directly to the Code of Conduct committee via the incident report form.

> Online Events and Communications Channels Checklist (Teaching Demonstrations, Community Discussions, Carpentries Instructor Training, Slack Channels, TopicBox)
> 

- > Inform the event host/meeting facilitator that there was an issue and send a report via the [incident report form](https://goo.gl/forms/KoUfO53Za3apOuOK2).
- > If the incident involves the event host/meeting facilitator, please complete the [incident report form](https://goo.gl/forms/KoUfO53Za3apOuOK2) and rest assured that confidentiality and your experience in our community is our first priority.

> 
>

**Comment by malvikasharan** [comment]
Hi @karenword, I have made some changes to make sure that in-person and online distinction is handled in a way that accommodates online workshops and conferences as well. 

Can you please review PR #875 to assess if it addresses the issue?

**Comment by karenword** [comment]
This is perfect -- thank you @malvikasharan !
