### ISSUE TITLE
Spreadsheet for opportunities to teach at workshops is deprecated but still linked in Teaching & Hosting

### ISSUE THREAD

**Issue by warrickball** [carpentries/docs.carpentries.org#882]
I'm currently training to certify as an Instructor and was looking around for whether teaching opportunities were listed somewhere. I came across the [Teaching & Hosting](https://docs.carpentries.org/topic_folders/hosts_instructors/index.html) page, which currently opens with
> Opportunities for certified instructors to teach Carpentries workshops are listed [here](https://docs.google.com/spreadsheets/d/1YhTAzEalDqKUowgej7aRa7E1K0XcB6ZezoVUt6VN2qY/edit#gid=0).

The link is to a Google Sheet that says instructors should sign up through AMY.

Separately, the [teaching section](https://docs.carpentries.org/topic_folders/for_instructors/current_instructors.html#teaching) for current Carpentries Instructors directs them to log in to AMY directly.

I expect the fix is to replace the link to the spreadsheet with either an internal link to the teaching section for current instructors, or to replace the link with instructions to look on AMY. I'm happy to propose a change via PR if either of these approaches is reasonable.

**Comment by maneesha** [comment]
Thanks for catching this @warrickball  
This has been fixed with #883
