### ISSUE TITLE
Link to rubric is broken in trainers_guide.md

### ISSUE THREAD

**Issue by mikblack** [carpentries/docs.carpentries.org#897]
In 

https://github.com/carpentries/docs.carpentries.org/edit/main/topic_folders/instructor_training/trainers_guide.md

at line 40:

`-  Use a [rubric][demo-rubric] to help you take notes.`

The "demo-rubric" expands to 

`Use a [rubric](https://carpentries.github.io/instructor-training/demos_rubric/) to help you take notes.`

when viewed at:

https://docs.carpentries.org/topic_folders/instructor_training/trainers_guide.html#running-a-teaching-demonstration

but I think the new rubric link should be:

https://carpentries.github.io/instructor-training/demos_rubric.html

**Comment by maneesha** [comment]
Thanks for catching this @mikblack 

@karenword this looks right; can you verify this is what you'd like that link to point to?

**Comment by karenword** [comment]
that's perfect -- thanks so much @mikblack
