### ISSUE TITLE
Link to "checkout process" is broken in new_instructors.md

### ISSUE THREAD

**Issue by cidule** [carpentries/docs.carpentries.org#901]
The link to "checkout process" is broken in https://github.com/carpentries/docs.carpentries.org/blob/main/topic_folders/for_instructors/new_instructors.md

Probably extra "/" in the link is the issue.

https://carpentries.github.io/instructor-training/checkout/ ==> https://carpentries.github.io/instructor-training/checkout

**Comment by maneesha** [comment]
Thanks for catching this @cidule 
This has been fixed with #902
