### ISSUE TITLE
Order of topic folders under Governance

### ISSUE THREAD

**Issue by kariljordan** [carpentries/docs.carpentries.org#907]
Can we change the order of the topic folders under [Governance](https://docs.carpentries.org/topic_folders/governance/index.html#governance) to the following?

- [The Carpentries Bylaws](https://docs.carpentries.org/topic_folders/governance/bylaws.html)
- [The Carpentries Executive Council](https://docs.carpentries.org/topic_folders/governance/executive-council.html#the-carpentries-executive-council)
- [The Carpentries Committee Policy](https://docs.carpentries.org/topic_folders/governance/committee-policy.html#the-carpentries-committee-policy)
- [The Carpentries Task Force Policy](https://docs.carpentries.org/topic_folders/governance/task-force-policy.html#the-carpentries-task-force-policy)
- [Lesson Programs](https://docs.carpentries.org/topic_folders/governance/lesson-program-policy.html#lesson-programs)

Also, #906 rearranges the EC section and consolidates information. It includes a section on EC Officers and links to the handbook detailing their roles and responsibilities. So, can we delete The [Carpentries Executive Council Officer Positions](https://docs.carpentries.org/topic_folders/governance/executive-council-officers.html)?

**Comment by maneesha** [comment]
Thanks @kariljordan I have just assigned myself to work on it this week.

**Comment by maneesha** [comment]
Thanks @kariljordan  PR #908  to fix this is available for your review.

**Comment by kariljordan** [comment]
I appreciate the quick turnaround @maneesha! The PR is exactly what I envisioned.
