### ISSUE TITLE
Use CSS to transform section titles to all-caps

### ISSUE THREAD

**Issue by bencomp** [carpentries/docs.carpentries.org#914]
In the Handbook, all level 1 headers appear in all-uppercase (all-caps), because in the source text they are written as such.
This means that the page title in the HTML metadata (`<head>` section) is also in all uppercase, hence one of the tabs in my browser is currently shouting *LESSON DEVELOPMENT*.

I would like to suggest to convert these headers to Title Case and – if it still appropriate to use uppercase headers – to use CSS text transforms for the effect, like it is done in the Workbench.

**Comment by maneesha** [comment]
Thanks @bencomp 
This is a stylistic change so I am turning to the expertise of our communications team, especially @acrall and @OscarSiba 

This a sample of what the menu and browser tab look like now:

![image](https://github.com/carpentries/docs.carpentries.org/assets/829690/b1e3c576-6845-42a1-bdfd-336623092b90)  
![image](https://github.com/carpentries/docs.carpentries.org/assets/829690/82a68498-4400-42e3-b1c9-020199bf3952)

and what they'd look like if we switched to Title Case:

![image](https://github.com/carpentries/docs.carpentries.org/assets/829690/ecedb969-080b-445b-be0f-bd618f48b2c6)
![image](https://github.com/carpentries/docs.carpentries.org/assets/829690/27a22ae4-e4a0-415a-ad63-a5d286bb67ce) 


It's not too difficult to implement the suggestion here but I will leave it to people with a better sense of style than me :-)

**Comment by bencomp** [comment]
Thanks for your quick response and preview, @maneesha! I will await the communications team's reactions.

**Comment by acrall** [comment]
I like the look of the change so vote for option 2. Thanks for the recommendation, @bencomp!

**Comment by maneesha** [comment]
Closed with #919
