### ISSUE TITLE
replace twitter refs with mastodon in all the email templates

### ISSUE THREAD

**Issue by ragamouf** [carpentries/docs.carpentries.org#946]
just noticed this now as I was using a template after a workshop. I would love to follow up this issue with my own PR that does exactly that! Anyways, keep me honest, I'll set a countdown timer for 7 days on this issue for myself.

**Comment by maneesha** [comment]
Hi @ragamouf  Thanks for catching this.  We would be happy to have you submit PRs to fix this.  If you can't get to it in the next week, no worries - one of our Core Team members can take care of this.

**Comment by ragamouf** [comment]
Thanks @maneesha, I've got a teaching demo this week, so it kind of makes sense for me to submit the PR.

**Comment by ragamouf** [comment]
PR #947 has been submitted.

**Comment by maneesha** [comment]
Fixed with #947
