### ISSUE TITLE
Make self-organized workshop form reqs consistent with steps 

### ISSUE THREAD

**Issue by ndporter** [carpentries/docs.carpentries.org#961]
The [Workshop Administration directions](https://docs.carpentries.org/topic_folders/workshop_administration/workshop_admin_workflow.html#for-self-organised-workshops) for self-organized workshop start with submitting the self-organized workshop request form before any instructions about making a workshop webpage:
> 1. Host submits the [Carpentries workshop request form](https://amy.carpentries.org/forms/workshop/). There is no fee (suggested or mandated) for a Self-Organised workshop.
> 2. Regional Coordinator reminds them that as a Self-Organised workshop they will have access to our surveys but will not receive any other support in coordinating this workshop. Read more about recruiting Instructors and Helpers in [the workshop FAQ](https://carpentries.org/workshop_faq/#if-i-need-help-recruiting-instructors-supporting-instructors-andor-helpers-for-a-self-organised-workshop-what-are-my-options).
> 3. Regional Coordinator reminds instructors to set up a workshop website using the [workshop template](https://github.com/carpentries/workshop-template).

However, the [request form](https://amy.carpentries.org/forms/self-organised/) will not allow submission without completing the  `Please share your workshop URL` question for a standard 2-day format workshop, returning the error below:
> This field is required if workshop format is standard two-day Carpentries workshop.

Either the force response needs to be removed (e.g. make it optional) or the directions need to be changed to reflect the correct order.

**Comment by maneesha** [comment]
I would recommend that the workshop website needs to be set up first, before submitting the form.  @sheraaronhurt  can you please let me know what you think?

**Comment by sheraaronhurt** [comment]
@maneesha @ndporter yes, you are correct. We should inform Instructors/Hosts to create the website **first** before submitting the request form

**Comment by maneesha** [comment]
Thanks.  I have opened a PR here:
https://github.com/carpentries/docs.carpentries.org/pull/962

@sheraaronhurt  in skimming that page, I see some other outdated information such as people's roles/titles.  I'm going to open a new issue to review that.
