### ISSUE TITLE
Out of date roles/titles and other information for workshop administration

### ISSUE THREAD

**Issue by maneesha** [carpentries/docs.carpentries.org#963]
On the [Workshop Administration Workflow](https://docs.carpentries.org/topic_folders/workshop_administration/workshop_admin_workflow.html#workshop-administration-workflow) page there are some outdated references to people's titles/roles and outdated internal workflows.

**About roles/titles**
* Do we still want to reference the "Regional Coordinator" role? 
* What should the roles of Deputy Director of Workshops and Meetings and Operations Manager change to? 

**About workflows**
There is a lot here I am not sure we are still doing - either that we don't do at all, or that is replaced by tools like automated emails.  Most of this information also seems internal rather than public, so I am not sure if we need to have this in a public facing document at all.

@sheraaronhurt  Let me know if you want to make changes to this page, or if you want to take this page down completely.

**Comment by sheraaronhurt** [comment]
@maneesha, we can remove it completely. Especially since we do not have RCs anymore

**Comment by maneesha** [comment]
Closing this with #962
